import type { Metadata } from "next";

import "@/accets/css/globals.css";
import TanstaqProvider from "@/entityes/providers/TanstackProvider";
import { QueryClient } from "@tanstack/react-query";
import { fetchGet } from "@/shared/utils/fetchers";
import { TPageSeo } from "@/shared/types/main_types";
import {
  API_URL,
  MainPageSeo_Prefix,
  MainPageSEOPath,
} from "@/shared/utils/consts";
import ThisThemeProvider from "@/entityes/providers/ThisThemeProvider";
import HeaderLayout from "@/entityes/components/HeaderLayout";
import FooterLayout from "@/entityes/components/FooterLayout";
import getCacheQueryClient from "@/entityes/providers/getQueryCache";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const query = getCacheQueryClient();
  const result = await query.fetchQuery({
    queryKey: [MainPageSeo_Prefix],
    queryFn: async () => {
      return await fetchGet<TPageSeo>(`${API_URL}/${MainPageSEOPath}`);
    },
  });

  return {
    title: result?.data.title,
    description: result?.data.description,
    authors: [{ name: result?.data.author }],
    creator: result?.data.creator,
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className="light h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <TanstaqProvider>
          <ThisThemeProvider>
            <HeaderLayout />
            <main className="flex-1">{children}</main>
            <FooterLayout />
          </ThisThemeProvider>
        </TanstaqProvider>
      </body>
    </html>
  );
}
