import type { Metadata } from "next";

import "@/accets/css/globals.css";
import TanstaqProvider from "@/entityes/providers/TanstackProvider";

import ThisThemeProvider from "@/entityes/providers/ThisThemeProvider";
import HeaderLayout from "@/entityes/components/HeaderLayout";
import FooterLayout from "@/entityes/components/FooterLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className="light h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col px-2 relative">
        <div className="hidden sm:block absolute z-0 top-0 left-0 w-full h-225 bg-green-500/50 dark:bg-chocolate/50 [clip-path:polygon(0_0,100%_0,100%_12%,0_60%)]"></div>
        <TanstaqProvider>
          <ThisThemeProvider>
            <HeaderLayout />
            <main className="w-full lg:max-w-240 lg:mx-auto flex-1">
              {children}
            </main>
            <FooterLayout />
          </ThisThemeProvider>
        </TanstaqProvider>
      </body>
    </html>
  );
}
